FROM debian:latest

# Установка необходимых пакетов
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    yara \
    git \
    sqlite3 \
    sudo \
    && apt-get clean

# Установка Python-зависимостей
RUN pip3 install --break-system-packages colorama requests bs4

# Создание пользователя с минимальными правами
RUN useradd -m appuser && echo "appuser:1234" | chpasswd && adduser appuser sudo

# Создание рабочей директории
WORKDIR /app

# Копирование файлов скрипта и правил
COPY app/main.py /app/main.py
COPY app/db_handler.py /app/db_handler.py
COPY app/exploits.py /app/exploits.py
COPY yara_rulesets/general_rules.yar /app/general_rules.yar
COPY yara_rulesets/additional_rulesets/debian/debian_additional_rules.yar /app/debian_additional_rules.yar

# Изменение владельца файлов
RUN chown -R appuser:appuser /app

# Переключение на пользователя appuser
USER appuser

# Команда для запуска скрипта
CMD ["python3", "main.py", "general_rules.yar", "debian_additional_rules.yar"]